- name: spc
  become: yes
  hosts: all
  tasks:
    - name: service_file
      copy:
        src: /home/sai/spc.service
        dest: /etc/systemd/system/spc.service
    - name: Restart service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: spc.service 
